name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    name: CI on ${{ matrix.cfg.os }}, Python ${{ matrix.cfg.python-version }}
    runs-on: ${{ matrix.cfg.os }}

    strategy:
      fail-fast: false
      matrix:
        cfg:
          - python-version: 3.9
            os: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          python-version: ${{ matrix.cfg.python-version }}
          environment-file: devtools/conda-envs/test-env.yaml

          activate-environment: test
          auto-update-conda: true
          auto-activate-base: false
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Conda Environment Information
        shell: powershell
        run: |
          conda info
          conda list

      - name: Build GUI
        shell: powershell
        run: |
          python setup.py build_gui

      - name: Install Package
        shell: powershell
        run: |
          pip install .

      - name: Check CLI
        shell: powershell
        run: |
          molesp --help
